spring:
  application:
    name: nyano
  datasource:
    url: jdbc:mysql://localhost:3306/nyano
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        'format_sql': true
        'use_sql_comments': true
  mail:
    host: smtp.gmail.com
    port: 587
    username: giahung112358@gmail.com
    password: xxkxexdajpkjlqbu
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: otp-group_id
      auto-offset-reset: earliest
      enable-auto-commit: true

